### ISSUE TITLE
感谢提供rxv设计思路

### ISSUE THREAD

**Issue by cevio** [sl1673495/react-composition-api#1]
非常感谢提供这样一种思路，已被使用在以下架构中:
- [TypeClient](https://github.com/flowxjs/TypeClient)
- [TypeClient-Template](https://github.com/flowxjs/TypeClient-Template)

虽然我没有直接使用您的`rxv`，但是还是非常感谢。不使用的原因是我需要定义`useStore`为`useContextState`函数，同时之后将会稍微修改内部逻辑。该项目为公司内部架构，如果之后开源，那么我将会声明这块架构采用了您的架构。
再次感谢!

> 很多开发者都可能还没有意识到你的这种模式将会为react带来多大的便利，我相信这是一种很好的思路。对于小白而言，都不会懂的。

**Comment by sl1673495** [comment]
非常开心能够帮到你~
